// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBllUGpIAX2YqGIs5IgVW6IdXznoYLd8t0',
    appId: '1:1051728860781:web:d02f8720f336a1da2b1164',
    messagingSenderId: '1051728860781',
    projectId: 'exercise5a-1a4ce',
    authDomain: 'exercise5a-1a4ce.firebaseapp.com',
    storageBucket: 'exercise5a-1a4ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL4p0TtQZ5rGrFQEZ9rb4p1b38K8s5n-4',
    appId: '1:1051728860781:android:a6276ba31f9891aa2b1164',
    messagingSenderId: '1051728860781',
    projectId: 'exercise5a-1a4ce',
    storageBucket: 'exercise5a-1a4ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90TIyiXtBb6FogiWRDTh3Hic2qL6RFxM',
    appId: '1:1051728860781:ios:302bfa9eadb691412b1164',
    messagingSenderId: '1051728860781',
    projectId: 'exercise5a-1a4ce',
    storageBucket: 'exercise5a-1a4ce.firebasestorage.app',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90TIyiXtBb6FogiWRDTh3Hic2qL6RFxM',
    appId: '1:1051728860781:ios:302bfa9eadb691412b1164',
    messagingSenderId: '1051728860781',
    projectId: 'exercise5a-1a4ce',
    storageBucket: 'exercise5a-1a4ce.firebasestorage.app',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBllUGpIAX2YqGIs5IgVW6IdXznoYLd8t0',
    appId: '1:1051728860781:web:43ddb7f5665f97562b1164',
    messagingSenderId: '1051728860781',
    projectId: 'exercise5a-1a4ce',
    authDomain: 'exercise5a-1a4ce.firebaseapp.com',
    storageBucket: 'exercise5a-1a4ce.firebasestorage.app',
  );
}
