// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK06j8VFnQXZ2SsQfNd50TgY2YZDjl0iw',
    appId: '1:416350345391:web:202a60fe365bb6b1d21c5a',
    messagingSenderId: '416350345391',
    projectId: 'exercise6-a672a',
    authDomain: 'exercise6-a672a.firebaseapp.com',
    storageBucket: 'exercise6-a672a.firebasestorage.app',
    measurementId: 'G-BBW9K3E36J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY5jOfkyIwQVnzsEMiXwKWn4tRSY9OyiU',
    appId: '1:416350345391:android:b25a84561daea7f0d21c5a',
    messagingSenderId: '416350345391',
    projectId: 'exercise6-a672a',
    storageBucket: 'exercise6-a672a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsSn6PXRgAkURjDcb3CnVMG56dWNP0Uz4',
    appId: '1:416350345391:ios:314887fe49ca7432d21c5a',
    messagingSenderId: '416350345391',
    projectId: 'exercise6-a672a',
    storageBucket: 'exercise6-a672a.firebasestorage.app',
    iosBundleId: 'com.example.exercise6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsSn6PXRgAkURjDcb3CnVMG56dWNP0Uz4',
    appId: '1:416350345391:ios:314887fe49ca7432d21c5a',
    messagingSenderId: '416350345391',
    projectId: 'exercise6-a672a',
    storageBucket: 'exercise6-a672a.firebasestorage.app',
    iosBundleId: 'com.example.exercise6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK06j8VFnQXZ2SsQfNd50TgY2YZDjl0iw',
    appId: '1:416350345391:web:ebf9584bf1f6708bd21c5a',
    messagingSenderId: '416350345391',
    projectId: 'exercise6-a672a',
    authDomain: 'exercise6-a672a.firebaseapp.com',
    storageBucket: 'exercise6-a672a.firebasestorage.app',
    measurementId: 'G-NG63CFKFC2',
  );
}
